config/routes.rb
Rails.application.routes.draw do
  get "/signup", to:"users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"

  resources :users
  root to: 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {maximum: 20}
  validates :email, presence: true, length: {maximum: 255}, uniqueness: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session
      log_in user
      redirect_to user_path(user)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to root_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :logged_in_user

  def show
    @user = User.find(params[:id])
  end

  def new
  end
  
  def index
    @users = User.all
  end

  def create
    user = User.new(user_params)
    if user.save
      reset_session
      log_in user
      redirect_to user_path(user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        redirect_to login_path, status: :see_other
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        reset_session
        @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/3209bac9df.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render 'shared/header' %>
    </header>

    <main class="mb-auto">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">
            <span>Bookers</span>
        </a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
                <% if logged_in? %>
                    <li class="nav-item">
                        <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
                        <i class="fa-solid fa-house"></i> Home
                        <% end %>
                    </li>
                    <li class="nav-item">
                        <%= link_to users_path, class: 'nav-link text-light' do %>
                        <i class="fa-solid fa-users"></i> Users
                        <% end %>
                    </li>
                    <li class="nav-item">
                        <%= link_to users_path, class: 'nav-link text-light' do %>
                        <i class="fa-solid fa-book-open"></i> Books
                        <% end %>
                    </li>
                    <li class="nav-item">
                        <%= link_to logout_path, method: :delete, class: 'nav-link text-light' do %> 
                        <i class="fa-solid fa-right-from-bracket"></i> Log out
                        <% end %>
                    </li>
                
                <% else %>
                    <li class="nav-item">
                        <%= link_to root_path, class: 'nav-link text-light' do %>
                        <i class="fa-solid fa-house"></i> Home
                        <% end %>
                    </li>
                    <li class="nav-item">
                        <%= link_to root_path, class: 'nav-link text-light' do %>
                        <i class="fa-solid fa-link"></i> About
                        <% end %>
                    </li>
                    <li class="nav-item">
                        <%= link_to signup_path, class: 'nav-link text-light' do %>
                        <i class="fa-solid fa-user-plus"></i> Sign up
                        <% end %>
                    </li>
                    <li class="nav-item">
                        <%= link_to login_path, class: 'nav-link text-light' do %>
                        <i class="fa-solid fa-right-to-bracket"></i> Log in
                        <% end %>
                    </li>             
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/users/index.html.erb
<h1>Users#index</h1>
<ul>
    <%= %>
</ul>

app/views/users/new.html.erb
<div class="container">
    <div class="row">
      <div class="col-sm-12 col-lg-5 px-5 px-sm-0">
        <h2>Sign up</h2>
      
        <%= form_with model:User.new, method: :post do |f| %>
          
          <div class="field">
            <%= f.label :name %><br />
            <%= f.text_field :name %>
          </div>
          
          <div class="field">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
          </div>
        
          <div class="field">
            <%= f.label :password %>
            <br />
            <%= f.password_field :password, autocomplete: "new-password" %>
          </div>
        
          <div class="field">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
          </div>
        
          <div class="actions">
            <%= f.submit "Sign up", class: 'btn bnt-sm btn-success' %>
          </div>
        <% end %>
        
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<p>user_name: <%= @user.name %></p>
<p>user_email: <%= @user.email %></p>